# Generated by Django 2.1 on 2019-03-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190306_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.CharField(blank=True, choices=[('Short Hills 101', 'Short Hills 101'), ('Short Hills 103', 'Short Hills 103'), ('Center Valley', 'Center Valley'), ('Austin', 'Austin'), ('Waltham', 'Waltham'), ('Irvine', 'Irvine'), ('Santa_Clara', 'Santa Clara'), ('Charlotte', 'Charlotte'), ('Chicago', 'Chicago'), ('Atlanta', 'Atlanta'), ('Naperville', 'Naperville'), ('Orange', 'Orange'), ('Portland', 'Portland'), ('Reston', 'Reston'), ('San Francisco', 'San Francisco'), ('Dallas', 'Dallas'), ('London', 'London'), ('Dublin', 'Dublin'), ('Marlow', 'Marlow'), ('Cardiff', 'Cardiff'), ('Shelton', 'Shelton'), ('New York City', 'New York City'), ('Portland', 'Portland'), ('Independence', 'Independence'), ('Mississauga', 'Mississauga'), ('Calgary', 'Calgary'), ('Mumbai', 'Mumbai'), ('Ashburn', 'Ashburn'), ('Seatle', 'Seatle'), ('Sydney', 'Sydney'), ('Singapore', 'Singapore'), ('London', 'London')], max_length=30),
        ),
    ]
